name: kinny
description: Flutter SDK for kin
version: 0.0.1
author: Kinny.io development team 
homepage: https://kinny.io

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  fixnum: ^0.10.11
  crypto: ^2.1.5
  decimal: ^0.3.5
  flutter_sodium: ^0.1.8
  pointycastle: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter