name: kin_sdk
description: A new flutter plugin project.
version: 0.0.1
author:
homepage: "https://www.kinny.io"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  crypto: ^2.1.5
  protobuf: ^1.0.1
  grpc: ^2.3.0
  logging: ^0.11.4
  fixnum: ^0.10.11



dev_dependencies:
  flutter_test:
    sdk: flutter