name: kin_sdk
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  fixnum: ^0.10.11
  crypto: ^2.1.5
  decimal: ^0.3.0
  tweetnacl: ^0.3.2
  toml: ^0.6.0
  pointycastle: ^1.0.0
  unorm_dart: ^0.1.2
  grpc: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter