name: kin_sdk
description: A new flutter plugin project.
version: 0.0.1
author:
homepage: "https://www.kinny.io"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  crypto: ^2.1.5
  protobuf: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.kinny.kin
        pluginClass: KinSdkPlugin
      ios:
        pluginClass: KinSdkPlugin