name: kin_sdk_example_console
description: A sample command-line application.
# version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  kin_base:
    path: ../../base
  kin_base_storage:
    path: ../../base_storage

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
