name: kin_base
description: Flutter SDK for kin
version: 0.0.1
author: Kinny.io development team 
homepage: https://kinny.io

environment:
  sdk: ">=2.7.0 <3.0.0"
#  flutter: ">=1.17.0 <2.0.0"

dependencies:
#  flutter:
#    sdk: flutter
  #stellar_flutter_sdk: ^1.1.2
  pinenacl: ^0.1.5
  eventsource: ^0.2.3 # Should be substituted, not maintained package.
  base32: ^1.1.2
  fast_base58: ^0.1.9
  http: ^0.12.2
  sse_client: ^0.0.3
  fixnum: ^0.10.11
  protobuf: ^1.0.1
  crypto: ^2.1.5
  decimal: ^0.3.5
  pointycastle: ^2.0.0
  argon2: ^1.0.0-no-null-safety
  grpc: ^2.9.0
  logging: ^0.11.4
  toml: ^0.6.0
  path: ^1.8.0
  kin_base_storage:
    git:
      url: https://kinny-ci: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@github.com/kinnytips/kin-flutter-sdk.git
      path: base_storage

dev_dependencies:
  test: ^1.16.0
