name: kin_base
description: Flutter SDK for kin
version: 2.0.0
author: Kinny.io development team 
homepage: https://kinny.io

environment:
  sdk: '>=2.12.0 <3.0.0'
#  flutter: ">=1.17.0 <2.0.0"

dependencies:
#  flutter:
#    sdk: flutter
  #stellar_flutter_sdk: ^1.1.2
  pinenacl: ^0.3.3
  #eventsource: ^0.2.3 # Should be substituted, not maintained package.
  base32: ^2.0.0
  fast_base58: ^0.2.0
  http: ^0.13.3
  sse_client: ^0.1.0
  fixnum: ^1.0.0
  protobuf: ^2.0.0
  crypto: ^3.0.1
  decimal: ^1.3.0
  pointycastle: ^3.3.1
  argon2: ^1.0.1
  grpc: ^3.0.2
  logging: ^1.0.1
  toml: ^0.11.0
  path: ^1.8.0
  kin_base_storage:
    path: ../base_storage

  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  test: ^1.17.11
