name: kin_base
description: Flutter SDK for kin
version: 0.0.1
author: Kinny.io development team 
homepage: https://kinny.io

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  #stellar_flutter_sdk: ^1.1.2
  tweetnacl: ^0.3.2 # Just to make 'stellarfork'  work. Maybe remove in the future.
  eventsource: ^0.2.3 # Should be substituted, not maintained package.
  base32: ^1.1.2
  http: ^0.12.2
  fixnum: ^0.10.11
  crypto: ^2.1.5
  decimal: ^0.3.5
  flutter_sodium: ^0.1.8
  pointycastle: ^2.0.0
  protobuf: ^1.0.1
  grpc: ^2.3.0
  logging: ^0.11.4
  toml: ^0.6.0
  path: ^1.8.0
  kin_base_storage:
    path: ../base_storage

dev_dependencies:
  flutter_test:
    sdk: flutter