name: kin_base_storage
description: Kin base storage
version: 2.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fixnum: ^1.0.0
  protobuf: ^2.0.0

dev_dependencies:
  lints: ^1.0.1
  test: ^1.17.11
