name: Kin flutter SDK CI

on:
  push:
    branches: [ sdk-update ]
jobs:
  test-application:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.2.0'
    - name: Install Flutter dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter test test/*.dart
