name: Kin flutter SDK CI

on:
  push:
    branches: [ master ]
jobs:
  test-base-sdk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-java@v1
      with:
        java-version: '11.x'
    - uses: actions/checkout@v2
    - name: 'Move to BASE sdk folder'
      run: cd base
    - name: 'Verify folder'
      run: ls -al
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.20.0'
    - name: Install Flutter dependencies
      run: flutter pub get
    - name: Run tests
      run: flutter test test/*.dart
